"""no-reminders

Revision ID: 26ad5ab4d8c3
Revises: b0017c23f780
Create Date: 2025-10-12 18:44:55.804396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26ad5ab4d8c3'
down_revision: Union[str, Sequence[str], None] = 'b0017c23f780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration was redundant - reminders table was already dropped
    # in migration 155022032550. Keeping as no-op for migration history continuity.
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration was redundant - keeping as no-op for migration history continuity.
    pass
    # ### end Alembic commands ###
