"""budgets

Revision ID: 98adebd998a9
Revises: 1d47a52e8c04
Create Date: 2025-11-27 19:11:57.695325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98adebd998a9'
down_revision: Union[str, Sequence[str], None] = '1d47a52e8c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Create the enum type first
    budgetperiod = postgresql.ENUM('daily', 'weekly', 'monthly', 'yearly', name='budgetperiod')
    budgetperiod.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.Enum('daily', 'weekly', 'monthly', 'yearly', name='budgetperiod'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('alert_thresholds', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_budgets_category', 'budgets', ['category_id'], unique=False)
    op.create_index('idx_budgets_deleted_at', 'budgets', ['deleted_at'], unique=False)
    op.create_index('idx_budgets_is_active', 'budgets', ['is_active'], unique=False)
    op.create_index('idx_budgets_user_period', 'budgets', ['user_id', 'period'], unique=False)
    op.create_index(op.f('ix_budgets_category_id'), 'budgets', ['category_id'], unique=False)
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    op.create_index(op.f('ix_budgets_user_id'), 'budgets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_user_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_category_id'), table_name='budgets')
    op.drop_index('idx_budgets_user_period', table_name='budgets')
    op.drop_index('idx_budgets_is_active', table_name='budgets')
    op.drop_index('idx_budgets_deleted_at', table_name='budgets')
    op.drop_index('idx_budgets_category', table_name='budgets')
    op.drop_table('budgets')
    
    # Drop the enum type
    budgetperiod = postgresql.ENUM('daily', 'weekly', 'monthly', 'yearly', name='budgetperiod')
    budgetperiod.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
