"""vendor map

Revision ID: 29e76350fc0f
Revises: ac141cc48edb
Create Date: 2025-08-14 03:20:45.053767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e76350fc0f'
down_revision: Union[str, Sequence[str], None] = 'ac141cc48edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_map',
    sa.Column('vendor_name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_map_category_id'), 'vendor_map', ['category_id'], unique=False)
    op.create_index(op.f('ix_vendor_map_id'), 'vendor_map', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_map_vendor_name'), 'vendor_map', ['vendor_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_map_vendor_name'), table_name='vendor_map')
    op.drop_index(op.f('ix_vendor_map_id'), table_name='vendor_map')
    op.drop_index(op.f('ix_vendor_map_category_id'), table_name='vendor_map')
    op.drop_table('vendor_map')
    # ### end Alembic commands ###
