"""subcategories

Revision ID: ac141cc48edb
Revises: 155022032550
Create Date: 2025-08-11 20:21:08.400604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac141cc48edb"
down_revision: Union[str, Sequence[str], None] = "155022032550"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(
        op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False
    )
    op.create_foreign_key(
        "fk_categories_parent_id", "categories", "categories", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_categories_parent_id", "categories", type_="foreignkey")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###
