"""timezones

Revision ID: ce57ac7f8982
Revises: 08d2702f9c50
Create Date: 2025-10-16 16:46:40.302699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce57ac7f8982'
down_revision: Union[str, Sequence[str], None] = '08d2702f9c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True, comment="User's timezone (IANA timezone name, e.g., 'Asia/Kolkata')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
