"""optimizations

Revision ID: 08d2702f9c50
Revises: e5383fb9b05e
Create Date: 2025-10-14 01:36:03.988912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08d2702f9c50'
down_revision: Union[str, Sequence[str], None] = 'e5383fb9b05e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_categories_name_parent', 'categories', ['name', 'parent_id'], unique=True)
    op.create_index('idx_expenses_deleted_at', 'expenses', ['deleted_at'], unique=False)
    op.create_index('idx_expenses_timestamp', 'expenses', ['timestamp'], unique=False)
    op.create_index('idx_expenses_user_timestamp', 'expenses', ['user_id', 'timestamp'], unique=False)
    op.create_index('idx_expenses_vendor', 'expenses', ['vendor'], unique=False)
    op.create_index('idx_reminders_composite', 'reminders', ['user_id', 'is_active', 'next_trigger_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reminders_composite', table_name='reminders')
    op.drop_index('idx_expenses_vendor', table_name='expenses')
    op.drop_index('idx_expenses_user_timestamp', table_name='expenses')
    op.drop_index('idx_expenses_timestamp', table_name='expenses')
    op.drop_index('idx_expenses_deleted_at', table_name='expenses')
    op.drop_index('idx_categories_name_parent', table_name='categories')
    # ### end Alembic commands ###
