"""subcategories

Revision ID: ac141cc48edb
Revises: 155022032550
Create Date: 2025-08-11 20:21:08.400604

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac141cc48edb"
down_revision: Union[str, Sequence[str], None] = "155022032550"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_categories_name"))
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_categories_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_categories_parent_id", "categories", ["parent_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_constraint("fk_categories_parent_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_categories_parent_id"))
        batch_op.drop_index(batch_op.f("ix_categories_name"))
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=True)
        batch_op.drop_column("parent_id")
    # ### end Alembic commands ###
