"""reminder id

Revision ID: 1d47a52e8c04
Revises: 7df598c54836
Create Date: 2025-11-07 00:49:23.287491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d47a52e8c04'
down_revision: Union[str, Sequence[str], None] = '7df598c54836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('cron_job_id', sa.Integer(), nullable=True))
    op.drop_column('reminders', 'schedule_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('schedule_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('reminders', 'cron_job_id')
    # ### end Alembic commands ###
