"""reminder scheduler

Revision ID: 0caeb3505a72
Revises: ce57ac7f8982
Create Date: 2025-11-03 03:05:11.117665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0caeb3505a72'
down_revision: Union[str, Sequence[str], None] = 'ce57ac7f8982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('schedule_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'schedule_id')
    # ### end Alembic commands ###
