"""deodap

Revision ID: 8ec0ba8dc9e1
Revises: cache_table_2026
Create Date: 2026-01-24 23:19:46.509686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec0ba8dc9e1'
down_revision: Union[str, Sequence[str], None] = 'cache_table_2026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deodap_order_emails',
    sa.Column('gmail_message_id', sa.String(length=100), nullable=False),
    sa.Column('gmail_thread_id', sa.String(length=100), nullable=True),
    sa.Column('email_subject', sa.String(length=500), nullable=True),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_from', sa.String(length=200), nullable=True),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('order_name', sa.String(length=200), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('address_line', sa.String(length=500), nullable=True),
    sa.Column('city_state_pincode', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('whatsapp_sent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deodap_order_emails_gmail_message_id'), 'deodap_order_emails', ['gmail_message_id'], unique=True)
    op.create_index(op.f('ix_deodap_order_emails_id'), 'deodap_order_emails', ['id'], unique=False)
    op.create_index(op.f('ix_deodap_order_emails_order_id'), 'deodap_order_emails', ['order_id'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_deodap_order_emails_order_id'), table_name='deodap_order_emails')
    op.drop_index(op.f('ix_deodap_order_emails_id'), table_name='deodap_order_emails')
    op.drop_index(op.f('ix_deodap_order_emails_gmail_message_id'), table_name='deodap_order_emails')
    op.drop_table('deodap_order_emails')
    # ### end Alembic commands ###
