"""add_budgets_table

Revision ID: 38334bc8f2c6
Revises: c4b5b7cf4087
Create Date: 2026-04-05 03:24:10.809108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38334bc8f2c6'
down_revision: Union[str, Sequence[str], None] = 'c4b5b7cf4087'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False, comment="Parent-level category name (e.g., 'Food & Dining')"),
    sa.Column('amount_limit', sa.Float(), nullable=False),
    sa.Column('period', sa.String(), nullable=False, comment="'weekly' or 'monthly'"),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_lookup', ['user_id', 'category_name', 'period'], unique=False)
        batch_op.create_index('idx_budgets_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('processed_bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processed_bank_transactions_gmail_message_id'))
        batch_op.drop_index(batch_op.f('ix_processed_bank_transactions_id'))

    op.drop_table('processed_bank_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_bank_transactions',
    sa.Column('gmail_message_id', sa.VARCHAR(), nullable=False),
    sa.Column('bank', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('merchant', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_date', sa.DATETIME(), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(), nullable=True),
    sa.Column('whatsapp_sent', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('user_action', sa.VARCHAR(), nullable=True),
    sa.Column('expense_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gmail_message_id')
    )
    with op.batch_alter_table('processed_bank_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processed_bank_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processed_bank_transactions_gmail_message_id'), ['gmail_message_id'], unique=1)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_id'))
        batch_op.drop_index('idx_budgets_user_active')
        batch_op.drop_index('idx_budgets_lookup')

    op.drop_table('budgets')
    # ### end Alembic commands ###
